config/routes.rb
MyApp::Application.routes.draw do
  resources :lendings

  resources :users

  resources :items

  root :to => 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
	scope :available, where( :rating => 3 )
	scope :available2, where( 'rating > 2' )

	belongs_to :user
	has_many :lendings

	attr_accessible :name, :rating, :description, :user_id
	validates_length_of :name, :minimum=>1
	validate :correct_rating
	validate :correct_user

	def correct_user
		# http://apidock.com/rails/ActiveModel/Errors
		errors.add( :user_id, 'User ID not found!' ) unless User.exists? user_id
	end

	def correct_rating
		 errors.add( :rating, 'Raiting not correct' ) unless (1..5).step(1).include?(rating)
	end

end

app/models/lending.rb
class Lending < ActiveRecord::Base
  attr_accessible :user_id, :item_id, :lending_end, :lending_start
  belongs_to :item
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :username

  has_many :items,  :dependent => :delete_all
  has_many :lendings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController
  # GET /lendings
  def index
    @lendings = Lending.all
  end

  # GET /lendings/new
  def new
    @lending = Lending.new
  end

  # POST /lendings
  def create
    @lending = Lending.new(params[:lending])

    if @lending.save
        redirect_to lendings_path, notice: 'Lending was successfully created.'
    else
        render action: "new"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.haml
= form_for(@item) do |f|
  - if @item.errors.any?
    #error_explanation
      %h2
        = pluralize(@item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg
  .field
    %p
      = f.label :name
      %br/
      = f.text_field :name
      %p
        = f.label :description
        %br/
        = f.text_field :description
        %p
          = f.label :rating
          %br/
          = f.text_field :rating
          %p
            = f.label :user_id
            %br/
            = f.select :user_id, options_for_select( User.all.collect { |p| [ p.username, p.id ] } )
  .actions
    = f.submit

app/views/items/edit.html.haml
%h1 Editing item
= render 'form'

= link_to 'Show', @item

\#{link_to 'Back', items_path}

app/views/items/index.html.haml
%h1 Listing items
%table
  %tr
    %th Name
    %th Beschreibung
    %th Berwertung
    %th Besitzer
    %th
    %th
    %th
  - @items.each do |item|
    %tr
      %td= item.name
      %td= item.description
      %td= item.rating
      %td= item.user.username
      %td= link_to 'Show', item
      %td= link_to 'Edit', edit_item_path(item)
      %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Item', new_item_path
= link_to 'New User', new_user_path

app/views/items/new.html.haml
%h1 New item
= render 'form'
= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice
%p
  %b Name:
  %p= @item.name
  %b Description
  %p= @item.description
  %b Rating
  %p= @item.rating
  %b User ID
  %p= @item.user_id
= link_to 'Edit', edit_item_path(@item)



\#{link_to 'Back', items_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyApp
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header.header
      %h1
        = link_to "Fancy lendings", root_path
      %nav
        %ul
          %li
            = link_to "Users", users_path
          %li
            = link_to "Items", items_path
          %li
            = link_to "Lendings", lendings_path

    .content
      = yield

app/views/lendings/_form.html.haml
= form_for(@lending) do |f|
  - if @lending.errors.any?
    #error_explanation
      %h2
        = pluralize(@lending.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - @lending.errors.full_messages.each do |msg|
          %li= msg
  .field
    %p
      = f.label :user_id
      %br/
      = f.select :user_id, options_for_select( User.all.collect { |user| [ user.username, user.id ] } )
    %p
      = f.label :item_id
      %br/
      = f.select :item_id, options_for_select( Item.all.collect { |item| [ item.name, item.id ] } )
    %p
      = f.label :lending_start
      %br/
      = f.text_field :lending_start
    %p
      = f.label :lending_end
      %br/
      = f.text_field :lending_end

  .actions
    = f.submit

app/views/lendings/index.html.haml
%p#notice
  = notice
%h1 Listing items
%table
  %tr
    %th
      Objekt
    %th
      Von
    %th
      Ausgeliehen am
    %th
      Zurückgebracht am
    %th
    %th
    %th
  - @lendings.each do |lending|
    %tr
      %td
        = lending.item.name
      %td
        = lending.user.username
      %td
        = lending.lending_start
      %td
        = lending.lending_end
      %td
        = link_to 'Show', lending
      %td
        = link_to 'Edit', edit_lending_path(lending)
      %td
        = link_to 'Destroy', lending, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Leading', new_lending_path
= link_to 'New User', new_user_path

app/views/lendings/new.html.haml
%h1 New lending
= render 'form'
= link_to 'Back', items_path

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %> <%= link_to 'New Item', new_item_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%p#notice= notice
%p
  %b Username:
  = @user.username
%p
  %b Password:
  = @user.password


= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', users_path}